- name: Install flatpak
  become: true
  package:
    name: flatpak
    state: latest

- name: Add flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "{{ repository }}"
    method: user

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ packages }}"
    state: present
    method: user
